---
- hosts: web_servers
  gather_facts: false
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_become_pass: "{{ lookup('env', 'SUDO_PASSWORD') }}"
  tasks:
    - name: Test simple command
      command: echo "Hello, World!"
